### ISSUE TITLE
fail to download playlist with 2-digit serial number 

### ISSUE THREAD

**Issue by jortegon** [ashishmadeti/spotify-playlist-downloader#11]
I tried to download playlist number 13, however due code has a n[i], it splits the 13 in 1 and 3, making it imposible to download a playlist with a 2-digit number.
a possible solution is to change "replace" for "split"
                n = raw_input("Enter S.N. of playlist (seprated by comma): ").split(",")

**Comment by ashishmadeti** [comment]
Hi @jortegon 

Looks like you already have the solution. You can just create a pull request!

**Comment by jortegon** [comment]
I made the following changes 
1. Change the search service from gvsearch to ytsearch
2. Now it allows to fetch playlist with serial number with 2 or more digits
3. It saves the files to a folder named as the playlist

But I'm not alowed to publish my branch in order to make the pull request. 
Would yo give me permissions to do so?

**Comment by ashishmadeti** [comment]
@jortegon 

What you want to do is:
1. Create a **fork** of the repository. (You can do that by clicking on the **Fork** button on the top right corner of this page.)
2. Clone your fork to your local machine and make changes
3. Push your changes (you should be able to do that as _you_ own the forked repository)
4. Clicking on **x branch** of your fork of the repository should show an option to create a new Pull Request.

Let me know if you face any issues.

**Comment by ashishmadeti** [comment]
Fixed by #12
