### ISSUE TITLE
Where can I set environment variables?

### ISSUE THREAD

**Issue by hasnogaems** [ashishmadeti/spotify-playlist-downloader#14]
Is it instruction for linux or I can reproduce in on win10?

**Comment by ashishmadeti** [comment]
Although I have tested this only on a linux setup (Ubuntu 18.04), it should work on all environments supported by python.

But I will not be able to help you set it up in other environments (like Win10) as I don't know myself. You should be able to find instructions for setting environment variables on win10 by running a google search.
