### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by itsbrex** [ashishmadeti/spotify-playlist-downloader#2]
Only thing is the export to CSV site only displays like my 10 or so most recent playlists. Any idea how to show all? Saw a tip on that repo's issue page about pasting some custom js in console while on the site, but no luck.

Great little tool! Thanks!

Btw, not sure exactly how they're doing it, but these guys are able to pull the album art in so you may want to have a look: https://github.com/Ritiek/Spotify-Downloader

**Comment by itsbrex** [comment]
Everything was working perfectly and then all of a sudden it just stopped and is now throwing this error: 

```
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "download_from_csv.py", line 106, in <module>
    ydl.download([url])
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1791, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 709, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 538, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Any ideas?

**Comment by ashishmadeti** [comment]
Hi @brianroach. Thanks for appreciating. This doesn't seem to be a problem in the script itself ([503](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error) error most probably means that there is some issue with youtube). Have you tried again? It should work.
Do open a separate issue if the problem persists.

I will add the feature 'attach album-art to downloaded song' soon. I have opened a separate issue for it: #3.
