### ISSUE TITLE
Noob Help

### ISSUE THREAD

**Issue by SinowZoa** [ashishmadeti/spotify-playlist-downloader#4]
I'm really don't have knowledge of Python, so i don't know exactly how to "Install dependencies: pip install youtube_dl eyed3 unidecode (May require root priveleges)", hehe. Any tips?

**Comment by ashishmadeti** [comment]
Hi. I don't know how I missed this. Can you tell me what operating system you are using and do you have python installed?

**Comment by ghost** [comment]
@SinowZoa Sorry for the necro, but have you tried doing `pip install --user youtube_dl eyed3 unidecode`?
